### ISSUE TITLE
check_connectivity throws a warning on success

### ISSUE THREAD

**Issue by Bre77** [georgestarcher/Splunk-Class-httpevent#14]
Using Splunk 8.0.5, the check_connectivity() method throws a warning that the data payload is blank, which is most certainly true in this method, but shouldn't warrant a warning.

`Connectivity Check: http_status_code=400 http_message={"text":"No data","code":5}`

I have raised a PR that removes the warning from a status 400.

**Comment by dnoach** [comment]
Thank you, I thought that was strange. One thing different in my scenario is that I get 
`Connectivity Check: http_status_code=403 http_message={"text":"Invalid token","code":4}`

I know that my token is correct because I was able to curl with it...

**Comment by marksolaris** [comment]
Curious why this isn't merged yet, I hand-ported it to my install.

**Comment by Bre77** [comment]
> Curious why this isn't merged yet, I hand-ported it to my install.

I ended up writing my own implementation. This repo seems dead. https://github.com/Bre77/hass_splunk

**Comment by georgestarcher** [comment]
This project is dead. my newer one is now https://github.com/georgestarcher/splunk_hec_aio
