### ISSUE TITLE
Missing module 'requests'

### ISSUE THREAD

**Issue by simcen** [georgestarcher/Splunk-Class-httpevent#2]
Hi George

Thanks for the class, I really appreciate.
However, trying to get it running, I found an issue:
Your class imports a module named 'requests' which isn't available in a standalone python environment.
Can you please point out which module should be installed/used for that?

Thank you
Simon

**Comment by georgestarcher** [comment]
You need to install the requests module if your system doesn't have it. You typically use the pip install requests. Or whatever your system supports.
