### ISSUE TITLE
Support for Indexer Acknowledgement

### ISSUE THREAD

**Issue by mlcooper** [georgestarcher/Splunk-Class-httpevent#20]
What are your thoughts on doing an enhancement for supporting Indexer Acknowledgement, which is discussed [here](https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/AboutHECIDXAck)?

This would help with guaranteed delivery of data to Splunk.  If a message sent was not successfully acknowledged, then a retry would be attempted until it was delivered, or until some number of configurable retries failed.

**Comment by georgestarcher** [comment]
Sorry. That's not going to be supported by me. Way too much hassle to add the tracking etc.
