### ISSUE TITLE
Add host and source to Splunk-HEC module

### ISSUE THREAD

**Issue by matthias2** [georgestarcher/Splunk-Class-httpevent#22]
Module doesn't allow to easily update `source` and `host` when using `raw` endpoint.  Adding them to the url allows for `source` and `host` to be updated for the `raw` endpoint.
https://github.com/georgestarcher/Splunk-Class-httpevent/pull/21

**Comment by georgestarcher** [comment]
Closing this here because I have moved onto new Project of https://github.com/georgestarcher/splunk_hec_aio However I believe I didn't have host and source there on URL either. I will make an issue for it.
